### ISSUE TITLE
Date Field is Broken

### ISSUE THREAD

**Issue by Jayshua** [steirico/kirby-plugin-custom-add-fields#9] opened 2019-06-25 16:43 UTC
Looks like the date field's calendar widget doesn't work inside the add dialog. Also, I would have expected it to be on top of the dialog, not inside and cut off by the bottom of the dialog.

![image](https://user-images.githubusercontent.com/1654103/60116710-2f5e8180-973e-11e9-826a-0c4fbf5e565d.png)

**Comment by Jayshua** [comment] 2019-06-25 16:44
Oh, and this was current version of Firefox with Kirby 3.1.3.

**Comment by steirico** [comment] 2019-06-25 16:51
Could you provide the `addFields` part of the corresponding blueprint, please? Furthermore, is it then a site or a page blueprint?

**Comment by Jayshua** [comment] 2019-06-25 16:53
This is a page blueprint.

```
addFields:
  city:
    label: City
    type: text
    required: true
    icon: circle-outline

  date:
    label: Date
    type: date
    required: true
    icon: calendar

  title:
    label: Title
    type: text
    required: true
    icon: title
```

**Comment by steirico** [comment] 2019-07-01 21:09
Let's tear down this issue into two separated points:

1. The date field's calendar widget doesn't work inside the add dialog
2. Calendar widget's bottom part is hidden behind the dialog's buttons

Unfortunately, I was not able to reproduce (1) using [Starterkit](https://github.com/getkirby/starterkit) with kirby 3.1.3, the plugin installed by composer, using the provided add fields and testing in Firefox 67.0.4 on macOS. There might be a correlation with another plugin or custom CSS in the panel.

(2) is related to kirby's underlying [k-dialog](https://getkirby.com/docs/reference/plugins/ui/dialog) widget and the way [overflows are handled](https://github.com/getkirby/kirby/blob/80b69380e672565a849037232c9951d1e32774c8/panel/src/components/Dialogs/Dialog.vue#L233). I will file an issue to kirby in order to discuss the use case in this issue.

In the meantime you can get around (2) by the adding `index.css` to the plugin's folder and add the following content:
```css
.k-dialog-body {
  overflow: visible;
}
```

**Comment by steirico** [comment] 2019-07-14 17:29
Since

* I was not able to reproduce problem (1)
* I provided a possible solution for (2)
* and I filed an issue for (2) at https://github.com/getkirby/kirby/issues/1918

I will close this issue for now. Feel free to reopen it if there are any new insights.

**Comment by steirico** [comment] 2019-12-07 14:09
@Jayshua: Do you open the add dialog from a [pagetable](https://github.com/sylvainjule/kirby-pagetable) section? I am faced with problem (1) by doing so.

As the screenshot shows, css classes and selectors from `pagetable` and the underlaying [tbl-for-kirby](https://github.com/distantnative/tbl-for-kirby) are polluting tables within the custom add dialog.

![Screenshot 2019-12-07 at 14 58 02](https://user-images.githubusercontent.com/10421363/70375776-60083100-1902-11ea-8ee0-6f4cc8910523.png)

Consequently, the date field gets broken.

**Comment by Jayshua** [comment] 2019-12-08 15:03
Yes, that looks like what happened to me.

**Comment by steirico** [comment] 2019-12-08 15:17
OK. A solution is underway by the authors of `tbl-for-kirby` and `pagetable`.

**Comment by steirico** [comment] 2021-03-12 13:00
Closing since all related issues and merge requests are closed.

**Closed by steirico** 2021-03-12 13:00 UTC
